import type { Visitor } from "./types"

export const mockVisitors: Visitor[] = [
  {
    id: "v1",
    name: "John Smith",
    location: "Main Building",
    validFrom: "Mar 15, 2025",
    validTo: "Mar 20, 2025",
    validTimeFrom: "9:00 AM",
    validTimeTo: "6:00 PM",
    usageCount: 1,
    status: "active",
    pin: "123456",
  },
  {
    id: "v2",
    name: "Jane Doe",
    location: "Building A",
    validFrom: "Mar 16, 2025",
    validTimeFrom: "2:00 PM",
    validTimeTo: "5:00 PM",
    usageCount: 0,
    status: "active",
    pin: "654321",
  },
  {
    id: "v3",
    name: "Robert Johnson",
    location: "South Gate",
    validFrom: "Mar 10, 2025",
    validTo: "Mar 12, 2025",
    validTimeFrom: "All Day",
    usageCount: 2,
    status: "expired",
    pin: "111222",
  },
  {
    id: "v4",
    name: "Alice Williams",
    location: "Main Building",
    validFrom: "Mar 14, 2025",
    validTimeFrom: "10:00 AM",
    validTimeTo: "4:00 PM",
    usageLimit: 3,
    usageCount: 2,
    status: "active",
    pin: "333444",
  },
  {
    id: "v5",
    name: "Michael Brown",
    location: "Building B",
    validFrom: "Mar 5, 2025",
    validTo: "Mar 8, 2025",
    validTimeFrom: "All Day",
    usageCount: 5,
    status: "expired",
    pin: "555666",
  },
]

